### ISSUE TITLE
B-Roll Epic

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/av-club#57]

**Comment by sebastianebarb** [comment]
Need"
- [ ] Kids Playing 
- [ ] Making History on the Common in June (check with kathleen.vonjena@boston.gov)
- [ ] Boats
- [ ] Boston Marathon Crowds
- [ ] Boston Marathon Runners 

Potential need
- [ ] Snowstorms

**Comment by DACole** [comment]
will grab some boats before the summer is over. Boston Marathon was a rainy day, pretty much a wash. I can also keep an eye out for kids playing.

snow storms this  winter.

**Comment by DACole** [comment]
We need to add more b-roll to our log completely.

**Comment by DACole** [comment]
I am going to work on challenging myself to add more content to this folder consistently, I noticed that filming additional b-roll when filming a different project does not help, as that content gets organized in a way that is for that project rather than for the entire scope of content captured, and without having the ability to organize the data. 

I should specifically film b-roll for an hour a week and just add it to the a folder of b-roll shots and label them, that way there is a fresh stock of goodies for people to use.
